# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-11 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_indextypegoodsbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indextypegoodsbanner',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Typegoods', verbose_name='商品类型'),
        ),
        migrations.AlterField(
            model_name='indextypegoodsbanner',
            name='goods',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Goods', verbose_name='商品'),
        ),
    ]
