# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-12 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190111_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='gclick',
            field=models.IntegerField(default=1, verbose_name='点击量'),
        ),
    ]
