# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-13 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190112_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_selected',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, '支付宝支付'), (2, '微信支付')], default=1, verbose_name='支付方式'),
        ),
    ]
