# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-22 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190113_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.IntegerField(choices=[(2, '已支付'), (1, '待支付')], default=1, verbose_name='支付状态'),
        ),
    ]
