# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-22 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20190122_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='content',
            field=models.TextField(default='', verbose_name='评论'),
        ),
    ]
